In [4]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm


# Question. 1

## We are going to conduct a 2 tailed t-Test on 2 Independent samples with Numerical Data
We need to check whether the mean of both samples are different and
 Is there any significance difference between the two samples? 

### Assume Null hyposthesis as Ho: μ1 = μ2 (There is no difference in diameters of cutlets between two units).

### Thus Alternate hypothesis as Ha: μ1 ≠ μ2 (There is significant difference in diameters of cutlets between two units)

Significance 5%

alpha = 0.05

As it is a two-tailed test
  alpha/2 = 0.025

In [6]:
# Load the dataset
data = pd.read_csv('Cutlets.csv')
data.head(5)

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [7]:
data.describe()

Unit A     Unit B
count  35.000000  35.000000
mean    7.019091   6.964297
std     0.288408   0.343401
min     6.437600   6.038000
25%     6.831500   6.753600
50%     6.943800   6.939900
75%     7.280550   7.195000
max     7.516900   7.545900

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Unit A  35 non-null     float64
 1   Unit B  35 non-null     float64
dtypes: float64(2)
memory usage: 688.0 bytes


In [14]:
# 2-sample 2-tail ttest:   
p_value=stats.ttest_ind(data['Unit A'], data['Unit B'])
p_value

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

### Compare p_value with 'α' (Significane Level)
### If p_value is 	≠  'α' we failed to reject Null Hypothesis 
### If p_value is =  'α' we reject Null Hypothesis

### Here p_value ≠ α
### Hence, We fail to reject Null Hypothesis (There is no difference in diameters of cutlets between two units).

# Question. 2

### We are going to conduct a ANOVA Test on 4 Independent samples with Numerical Data
We need to check whether the mean of any of these samples are different or the same?

### Null Hypothesis: μ1 = μ2 = μ3 = μ4 .
### Alternative Hypthosis: Atleast One of them is Differente.

Significance 5%

alpha = 0.05

In [15]:
# Loading The dataset
data2 = pd.read_csv('LabTAT.csv')
data2.head(5)

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [16]:
data2.describe()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
count    120.000000    120.000000    120.000000     120.00000
mean     178.361583    178.902917    199.913250     163.68275
std       13.173594     14.957114     16.539033      15.08508
min      138.300000    140.550000    159.690000     124.06000
25%      170.335000    168.025000    188.232500     154.05000
50%      178.530000    178.870000    199.805000     164.42500
75%      186.535000    189.112500    211.332500     172.88250
max      216.390000    217.860000    238.700000     205.18000

In [17]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Laboratory 1  120 non-null    float64
 1   Laboratory 2  120 non-null    float64
 2   Laboratory 3  120 non-null    float64
 3   Laboratory 4  120 non-null    float64
dtypes: float64(4)
memory usage: 3.9 KB


In [18]:
# Anova ftest statistics: stats.f_oneway(column-1,column-2,column-3,column-4)
p_value=stats.f_oneway(data2.iloc[:,0],data2.iloc[:,1],data2.iloc[:,2],data2.iloc[:,3])
p_value

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

### Here p_value ≠ α
### Hence we fail to reject null hypothesis
### i.e. Accept alternate hypothesis (Atleast One of them is Differente).

# Question. 3

## We are going to conduct a Test of Independence using Chi-Square  test with Contingency table
We need to check whether the proportion of any of these samples are different or the same?

### Null Hypothesis: There is no association or dependency between the gender based buyer rations across regions
### Alternative Hypthosis: There is a significant association or dependency between the gender based buyer rations across regions

In [ ]:
# Significance 5%
# alpha = 0.05

# As it is a one-tailed test
alpha = 1-0.95 = 0.05

In [20]:
# Loading the Dataset
data3 = pd.read_csv('BuyerRatio.csv')
data3

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [46]:
data3.describe()

East         West        North       South
count    2.000000     2.000000     2.000000    2.000000
mean   242.500000   832.500000   743.500000  410.000000
std    272.236111   976.514465   866.205807  480.832611
min     50.000000   142.000000   131.000000   70.000000
25%    146.250000   487.250000   437.250000  240.000000
50%    242.500000   832.500000   743.500000  410.000000
75%    338.750000  1177.750000  1049.750000  580.000000
max    435.000000  1523.000000  1356.000000  750.000000

In [47]:
data3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   East    2 non-null      int64
 1   West    2 non-null      int64
 2   North   2 non-null      int64
 3   South   2 non-null      int64
dtypes: int64(4)
memory usage: 192.0 bytes


In [24]:
data3.drop(["Observed Values"], axis = 1, inplace = True)

In [25]:
data3

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [26]:
from scipy.stats import chi2_contingency

In [27]:
p_value = stats.chi2_contingency(data3)

In [28]:
p_value

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [29]:
p_value[1]

0.6603094907091882

### p-value (0.66)> α (0.05), hence we can't reject the null hypothesis
### There is no association or dependency between the gender based buyer rations across regions

# Question. 4

## We are going to conduct a Test of Independence using Chi-Square x2 test with Contingency table
We need to check whether the mean of any of these samples are different or the same?

### Null Hypothesis: μ1 = μ2 = μ3 = μ4 .
### Alternative Hypthosis: Atleast One of them is Differente.

In [ ]:
# Significance 5%
# alpha = 0.05

In [31]:
# Load the Dataset
data4 = pd.read_csv('Costomer+OrderForm.csv')
data4.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [37]:
data4.describe()

Phillippines   Indonesia       Malta       India
count           300         300         300         300
unique            2           2           2           2
top      Error Free  Error Free  Error Free  Error Free
freq            271         267         269         280

In [38]:
data4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Phillippines  300 non-null    object
 1   Indonesia     300 non-null    object
 2   Malta         300 non-null    object
 3   India         300 non-null    object
dtypes: object(4)
memory usage: 9.5+ KB


In [39]:
data4.Phillippines.value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [40]:
data4.Indonesia.value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [41]:
data4.Malta.value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [43]:
data4.India.value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [44]:
# Make a contingency table
obs=np.array([[271,267,269,280],[29,33,31,20]])
obs

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [45]:
# Chi2 contengency independence test
chi2_contingency(obs) # o/p is (Chi2 stats value, p_value, df, expected obsvations)

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [ ]:
# Hence p_value = 0.2771020991233135


### Here p_value ≠ α
### Hence we fail to reject null hypothesis
### i.e. Accept alternate hypothesis (Atleast One of them is Differente).